# Generated by Django 6.0.2 on 2026-03-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_library", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "artists",
                    models.ManyToManyField(
                        related_name="Genres", to="music_library.artist"
                    ),
                ),
            ],
        ),
    ]
