# Generated by Django 6.0.2 on 2026-03-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_library", "0002_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="artists",
            field=models.ManyToManyField(
                related_name="Genre", to="music_library.artist"
            ),
        ),
    ]
